#!/usr/bin/env python3
"""
RMMZ Studio - Project Sync Helper
Usage:
  python3 rmmz_sync.py load <project_path>
  python3 rmmz_sync.py save <project_path>
  python3 rmmz_sync.py save-find <project_path>
  python3 rmmz_sync.py verify <project_path>
  python3 rmmz_sync.py save-type <project_path> <Type> <json_file>
  python3 rmmz_sync.py save-chunks <project_path> <chunks_dir>
"""
import sys, os, json, glob, time, shutil

DB_FILES = ['Actors', 'Classes', 'Skills', 'Items', 'Weapons', 'Armors',
            'Enemies', 'Troops', 'States', 'CommonEvents', 'System', 'Tilesets']

KEY_MAP = {
    'actors': 'Actors', 'classes': 'Classes', 'skills': 'Skills',
    'items': 'Items', 'weapons': 'Weapons', 'armors': 'Armors',
    'enemies': 'Enemies', 'troops': 'Troops', 'states': 'States',
    'commonevents': 'CommonEvents', 'commonEvents': 'CommonEvents',
    'system': 'System', 'tilesets': 'Tilesets',
    'Actors': 'Actors', 'Classes': 'Classes', 'Skills': 'Skills',
    'Items': 'Items', 'Weapons': 'Weapons', 'Armors': 'Armors',
    'Enemies': 'Enemies', 'Troops': 'Troops', 'States': 'States',
    'CommonEvents': 'CommonEvents', 'System': 'System', 'Tilesets': 'Tilesets',
}

def load_project(project_path):
    data_dir = os.path.join(project_path, 'data')
    if not os.path.isdir(data_dir):
        print(f"ERROR: {data_dir} not found")
        return False
    studio_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(studio_dir, '_temp_db_load.js')
    lines = ['// Auto-generated by rmmz_sync.py', 'window.__RMMZ_DB = {};', '']
    for db_file in DB_FILES:
        filepath = os.path.join(data_dir, db_file + '.json')
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read().strip()
            lines.append('window.__RMMZ_DB.' + db_file + ' = ' + content + ';')
            print(f'  + {db_file}.json loaded ({len(content)} bytes)')
        else:
            print(f'  - {db_file}.json not found')
    mapinfos_path = os.path.join(data_dir, 'MapInfos.json')
    if os.path.exists(mapinfos_path):
        with open(mapinfos_path, 'r', encoding='utf-8') as f:
            content = f.read().strip()
        lines.append('\nwindow.__RMMZ_MAPINFOS = ' + content + ';')
        print('  + MapInfos.json loaded')
    lines.append('\nwindow.__RMMZ_MAPS = {};')
    map_files = sorted(glob.glob(os.path.join(data_dir, 'Map[0-9]*.json')))
    for mf in map_files:
        fname = os.path.basename(mf)
        map_id = fname.replace('Map', '').replace('.json', '')
        try:
            map_id_int = int(map_id)
        except ValueError:
            continue
        with open(mf, 'r', encoding='utf-8') as f:
            content = f.read().strip()
        lines.append('window.__RMMZ_MAPS[' + str(map_id_int) + '] = ' + content + ';')
        print(f'  + {fname} loaded')
    plugins_path = os.path.join(project_path, 'js', 'plugins.js')
    if os.path.exists(plugins_path):
        with open(plugins_path, 'r', encoding='utf-8') as f:
            content = f.read().strip()
        if '$plugins' in content:
            start = content.index('[')
            end = content.rindex(']') + 1
            plugin_json = content[start:end]
            lines.append('\nwindow.__RMMZ_PLUGINS = ' + plugin_json + ';')
            print('  + plugins.js loaded')
    escaped_path = project_path.replace('\\', '/')
    lines.append('\nwindow.__RMMZ_PROJECT_PATH = "' + escaped_path + '";')
    lines.append('')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'\n-> {output_path} generated ({os.path.getsize(output_path)} bytes)')
    return True

def save_project(project_path):
    studio_dir = os.path.dirname(os.path.abspath(__file__))
    export_path = os.path.join(studio_dir, '_temp_db_export.json')
    if not os.path.exists(export_path):
        print(f"ERROR: {export_path} not found")
        return False
    with open(export_path, 'r', encoding='utf-8') as f:
        export_data = json.load(f)
    data_dir = os.path.join(project_path, 'data')
    saved = 0
    if 'database' in export_data:
        for key, data in export_data['database'].items():
            rmmz_name = KEY_MAP.get(key, key)
            filepath = os.path.join(data_dir, rmmz_name + '.json')
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, separators=(',', ':'))
            print(f'  + {rmmz_name}.json saved')
            saved += 1
    if 'maps' in export_data:
        for map_id_str, map_data in export_data['maps'].items():
            map_id = int(map_id_str)
            fname = 'Map' + str(map_id).zfill(3) + '.json'
            filepath = os.path.join(data_dir, fname)
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(map_data, f, ensure_ascii=False, separators=(',', ':'))
            print(f'  + {fname} saved')
            saved += 1
    if 'mapInfos' in export_data:
        filepath = os.path.join(data_dir, 'MapInfos.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(export_data['mapInfos'], f, ensure_ascii=False, separators=(',', ':'))
        print('  + MapInfos.json saved')
        saved += 1
    if 'plugins' in export_data and export_data['plugins']:
        plugins_path = os.path.join(project_path, 'js', 'plugins.js')
        plugin_json = json.dumps(export_data['plugins'], ensure_ascii=False, indent=2)
        with open(plugins_path, 'w', encoding='utf-8') as f:
            f.write('// Generated by RMMZ Studio\nvar $plugins =\n' + plugin_json + ';\n')
        print('  + plugins.js saved')
        saved += 1
    print(f'\n-> {saved} files saved to {data_dir}')
    return True

def verify_project(project_path):
    data_dir = os.path.join(project_path, 'data')
    print(f'Project: {project_path}')
    print(f'Data dir: {data_dir}\n')
    for db_file in DB_FILES:
        filepath = os.path.join(data_dir, db_file + '.json')
        if os.path.exists(filepath):
            size = os.path.getsize(filepath)
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
            if isinstance(data, list):
                count = len([x for x in data if x is not None])
                sample = ''
                for item in data:
                    if item and isinstance(item, dict) and 'name' in item:
                        sample = ' (first: ' + item['name'] + ')'
                        break
                print(f'  {db_file:15s} {count:4d} items  {size:>8,d}B{sample}')
            else:
                print(f'  {db_file:15s}   object  {size:>8,d}B')
        else:
            print(f'  {db_file:15s}   NOT FOUND')
    map_files = sorted(glob.glob(os.path.join(data_dir, 'Map[0-9]*.json')))
    print(f'\n  Maps: {len(map_files)} files')
    for mf in map_files[:5]:
        with open(mf, 'r', encoding='utf-8') as f:
            md = json.load(f)
        w = md.get('width', '?')
        h = md.get('height', '?')
        ts = md.get('tilesetId', '?')
        print(f'    {os.path.basename(mf):12s} {w}x{h} tilesetId={ts}')

def save_find_project(project_path):
    home = os.path.expanduser('~')
    search_dirs = [
        os.path.join(home, 'Downloads'),
        os.path.join(home, 'Desktop'),
        os.path.dirname(os.path.abspath(__file__)),
    ]
    found = None
    for search_dir in search_dirs:
        if not os.path.isdir(search_dir):
            continue
        pattern = os.path.join(search_dir, '_temp_db_export*.json')
        matches = sorted(glob.glob(pattern), key=os.path.getmtime, reverse=True)
        for match in matches:
            age = time.time() - os.path.getmtime(match)
            print(f'  Found: {match} (age: {age:.0f}s)')
            if age < 300:
                found = match
                break
        if found:
            break
    if not found:
        print('ERROR: No recent _temp_db_export.json found (within 5 min)')
        return False
    print(f'\nUsing: {found}')
    studio_dir = os.path.dirname(os.path.abspath(__file__))
    std_path = os.path.join(studio_dir, '_temp_db_export.json')
    shutil.copy2(found, std_path)
    result = save_project(project_path)
    try:
        os.remove(found)
        print(f'  Cleaned up: {found}')
    except OSError:
        pass
    return result

def save_single_type(project_path, type_name, json_file):
    data_dir = os.path.join(project_path, 'data')
    if not os.path.isdir(data_dir):
        print(f"ERROR: {data_dir} not found")
        return False
    with open(json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    filepath = os.path.join(data_dir, type_name + '.json')
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, separators=(',', ':'))
    size = os.path.getsize(filepath)
    print(f'  + {type_name}.json saved ({size:,d}B)')
    return True

def save_from_chunks(project_path, chunks_dir):
    data_dir = os.path.join(project_path, 'data')
    if not os.path.isdir(data_dir):
        print(f"ERROR: {data_dir} not found")
        return False
    chunk_files = sorted(glob.glob(os.path.join(chunks_dir, 'chunk_*.txt')))
    if not chunk_files:
        print(f"ERROR: No chunk files in {chunks_dir}")
        return False
    full_json = ''
    for cf in chunk_files:
        with open(cf, 'r', encoding='utf-8') as f:
            full_json += f.read()
    print(f'Reassembled {len(chunk_files)} chunks ({len(full_json):,d} chars)')
    export_data = json.loads(full_json)
    studio_dir = os.path.dirname(os.path.abspath(__file__))
    export_path = os.path.join(studio_dir, '_temp_db_export.json')
    with open(export_path, 'w', encoding='utf-8') as f:
        json.dump(export_data, f, ensure_ascii=False)
    return save_project(project_path)

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    cmd = sys.argv[1]
    project = sys.argv[2]
    if cmd == 'load':
        load_project(project)
    elif cmd == 'save':
        save_project(project)
    elif cmd == 'save-find':
        save_find_project(project)
    elif cmd == 'save-type':
        if len(sys.argv) < 5:
            print('Usage: save-type <project> <TypeName> <json_file>')
            sys.exit(1)
        save_single_type(project, sys.argv[3], sys.argv[4])
    elif cmd == 'save-chunks':
        if len(sys.argv) < 4:
            print('Usage: save-chunks <project> <chunks_dir>')
            sys.exit(1)
        save_from_chunks(project, sys.argv[3])
    elif cmd == 'verify':
        verify_project(project)
    else:
        print(f'Unknown command: {cmd}')
        print(__doc__)
