// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
  {
    "name": "SRPG_Core",
    "status": true,
    "description": "SRPG Grid Battle System",
    "parameters": {
      "DefaultMov": "4",
      "DefaultAtkRange": "1",
      "TileSize": "48",
      "MoveSpeed": "5",
      "PortraitMode": "true",
      "PortraitScale": "1.5",
      "ActorConfig": "{\"3\": {\"atkRange\": 4, \"fireMode\": \"direct\"}, \"5\": {\"atkRange\": 3, \"fireMode\": \"arc\"}}",
      "EnemyConfig": "{}"
    }
  },
  {
    "name": "SRPG_TerrainConfig",
    "status": true,
    "description": "SRPG terrain tag and region ID configuration table v2.0",
    "parameters": {
      "TerrainTags": "[\"{\\\"tag\\\": \\\"0\\\", \\\"name\\\": \\\"\\\\uc77c\\\\ubc18\\\", \\\"terrainType\\\": \\\"none\\\", \\\"element\\\": \\\"\\\"}\", \"{\\\"tag\\\": \\\"1\\\", \\\"name\\\": \\\"\\\\ubb3c\\\\uae38\\\", \\\"terrainType\\\": \\\"surface\\\", \\\"element\\\": \\\"water\\\"}\", \"{\\\"tag\\\": \\\"2\\\", \\\"name\\\": \\\"\\\\ub3c5\\\\uc0d8\\\", \\\"terrainType\\\": \\\"surface\\\", \\\"element\\\": \\\"poison\\\"}\", \"{\\\"tag\\\": \\\"3\\\", \\\"name\\\": \\\"\\\\uc6a9\\\\uc554\\\", \\\"terrainType\\\": \\\"surface\\\", \\\"element\\\": \\\"fire\\\"}\", \"{\\\"tag\\\": \\\"4\\\", \\\"name\\\": \\\"\\\\uc5bc\\\\uc74c\\\", \\\"terrainType\\\": \\\"surface\\\", \\\"element\\\": \\\"ice\\\"}\", \"{\\\"tag\\\": \\\"5\\\", \\\"name\\\": \\\"\\\\uae30\\\\ub984\\\", \\\"terrainType\\\": \\\"surface\\\", \\\"element\\\": \\\"oil\\\"}\", \"{\\\"tag\\\": \\\"6\\\", \\\"name\\\": \\\"\\\\ucd95\\\\ubcf5\\\", \\\"terrainType\\\": \\\"surface\\\", \\\"element\\\": \\\"blessed\\\"}\", \"{\\\"tag\\\": \\\"7\\\", \\\"name\\\": \\\"\\\\uc800\\\\uc8fc\\\", \\\"terrainType\\\": \\\"surface\\\", \\\"element\\\": \\\"cursed\\\"}\", \"{\\\"tag\\\": \\\"8\\\", \\\"name\\\": \\\"\\\\uc5c4\\\\ud3d0\\\\ubb3c\\\", \\\"terrainType\\\": \\\"cover\\\", \\\"element\\\": \\\"\\\"}\", \"{\\\"tag\\\": \\\"9\\\", \\\"name\\\": \\\"\\\\ud3d0\\\\uc1c4\\\\ubcbd\\\", \\\"terrainType\\\": \\\"wall\\\", \\\"element\\\": \\\"\\\"}\", \"{\\\"tag\\\": \\\"10\\\", \\\"name\\\": \\\"\\\\uc218\\\\ud480\\\", \\\"terrainType\\\": \\\"bush\\\", \\\"element\\\": \\\"\\\"}\"]",
      "RegionElevations": "[\"{\\\"regionId\\\":\\\"0\\\",\\\"name\\\":\\\"중간지대\\\",\\\"elevType\\\":\\\"elevation\\\",\\\"elevationLevel\\\":\\\"2\\\",\\\"isStair\\\":\\\"false\\\"}\",\"{\\\"regionId\\\":\\\"1\\\",\\\"name\\\":\\\"낭떠러지\\\",\\\"elevType\\\":\\\"cliff\\\",\\\"elevationLevel\\\":\\\"0\\\",\\\"isStair\\\":\\\"false\\\"}\",\"{\\\"regionId\\\":\\\"2\\\",\\\"name\\\":\\\"저지대\\\",\\\"elevType\\\":\\\"elevation\\\",\\\"elevationLevel\\\":\\\"0\\\",\\\"isStair\\\":\\\"false\\\"}\",\"{\\\"regionId\\\":\\\"3\\\",\\\"name\\\":\\\"저-중 계단\\\",\\\"elevType\\\":\\\"elevation\\\",\\\"elevationLevel\\\":\\\"1\\\",\\\"isStair\\\":\\\"true\\\"}\",\"{\\\"regionId\\\":\\\"5\\\",\\\"name\\\":\\\"중-고 계단\\\",\\\"elevType\\\":\\\"elevation\\\",\\\"elevationLevel\\\":\\\"3\\\",\\\"isStair\\\":\\\"true\\\"}\",\"{\\\"regionId\\\":\\\"6\\\",\\\"name\\\":\\\"고지대\\\",\\\"elevType\\\":\\\"elevation\\\",\\\"elevationLevel\\\":\\\"4\\\",\\\"isStair\\\":\\\"false\\\"}\"]",
      "DefaultElevation": "2"
    }
  },
  {
    "name": "AltMenuScreen",
    "status": false,
    "description": "",
    "parameters": {}
  },
  {
    "name": "AltSaveScreen",
    "status": false,
    "description": "",
    "parameters": {}
  },
  {
    "name": "ButtonPicture",
    "status": false,
    "description": "",
    "parameters": {}
  },
  {
    "name": "TextPicture",
    "status": false,
    "description": "",
    "parameters": {}
  },
  {
    "name": "SRPG_Boot",
    "status": true,
    "description": "SRPG Core safety patch - error recovery, missing command fallback, and movement blocking guard.",
    "parameters": {}
  },
  {
    "name": "SRPG_SkillEditor",
    "status": true,
    "description": "SRPG Skill Editor - summary panel and popup launcher",
    "parameters": {}
  },
  {
    "name": "StandingManager",
    "status": true,
    "description": "Standing portrait DB management plugin",
    "parameters": {
      "emotionPresets": "normal,sternness,indignation,anger,rage,disdain,aversion,disgust,revulsion,concern,anxiety,fear,terror,satisfaction,amusement,joy,laughter,dejection,melancholy,sadness,grief,alertness,wonder,surprise,shock,wounded,battle,event",
      "portraits": "[]",
      "defaultSlots": "body,outfit,hair,expression,accessory",
      "layered": "[]",
      "standingWidth": "832",
      "standingHeight": "1216",
      "situationRatios": "1:1,3:2,2:3"
    }
  },
  {
    "name": "GahoSystem",
    "status": true,
    "description": "Gaho Divine Blessing System - Saju-based character natal chart engine",
    "parameters": {
      "ActorConfig": "{}"
    }
  },
  {
    "name": "SRPG_CombatAI",
    "status": true,
    "description": "SRPG Combat AI - Saju-based dual-layer (Ilgan/Ilji) enemy decision system",
    "parameters": {
      "ActorAIConfig": "{}",
      "EnemyAIConfig": "{}"
    }
  },
  {
    "name": "ActorSurname",
    "status": true,
    "description": "Actor surname field with full name display and text escape codes",
    "parameters": {
      "NameOrder": "sf",
      "Separator": " "
    }
  },
  {
    "name": "GridInventory",
    "status": true,
    "description": "Diablo 2 style grid inventory with per-character storage and hotkey slots",
    "parameters": {
      "DefaultGridCols": "8",
      "DefaultGridRows": "6",
      "HotkeySlots": "4",
      "DefaultItemSize": "1,1",
      "DefaultWeaponSize": "1,3",
      "DefaultArmorSize": "2,2",
      "DefaultKeyItemSize": "1,1"
    }
  },
  {
    "name": "MenuOverhaul",
    "status": true,
    "description": "Custom main menu with Character, Bonds, Items, Tactics, Journal, and System tabs.",
    "parameters": {
      "PartyDisplayHeight": "120",
      "CommandWidth": "180"
    }
  }
]
